# Generated by Django 3.2 on 2022-11-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rate', '0003_auto_20221124_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='gender',
            field=models.BooleanField(default=0, help_text='عدد 0 نشان دهنده زن و عدد 1 مرد می باشد', verbose_name='جنیست'),
        ),
    ]
