# Generated by Django 3.2 on 2022-11-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rate', '0005_auto_20221125_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
