# Generated by Django 3.2 on 2022-11-24 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rate', '0006_alter_survey_create_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfessorLectureSemester',
            new_name='Class',
        ),
    ]
